development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:7b77cd3e4d24067966a6a7082b556cce@angelfish.redistogo.com:11719/
  host: angelfish.redistogo.com
  port: 11719
  password: 7b77cd3e4d24067966a6a7082b556cce
